#language: java
sudo: required
before_install:
#  - yes y | sudo python -m pip uninstall pip
#  - wget https://bootstrap.pypa.io/get-pip.py
#  - sudo python get-pip.py 
#  - pwd
#  - which pip
  - sudo pip install pyOpenSSL ndg-httpsclient pyasn1
  - sudo pip install --upgrade pip 
  - sudo pip install robotframework-seleniumlibrary
  - mkdir -p target/robotframework/libraries
#  - ls -lR /usr/local/lib/python2.7/ ~
  - cp -r /usr/local/lib/python2.7/dist-packages/* target/robotframework/libraries/ 
  - cp -r /usr/local/lib/python2.7/dist-packages/pip/_vendor/* target/robotframework/libraries/ 
  - find target/robotframework/libraries -type f -iname webdriver.py
  - find target/robotframework/libraries -type d -iname urllib3
script: mvn install
