language: java
sudo: required
before_install:
#  - yes y | sudo python -m pip uninstall pip
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo python get-pip.py 
  - pwd
  - which pip 
  - sudo pip install pyOpenSSL ndg-httpsclient pyasn1
  - sudo pip install robotframework-seleniumlibrary
  - mkdir -p target/robotframework/libraries
  - ls -ltr /usr/local/lib/python2.7/site-packages
#  - find / -type d -name site-packages
#  - find / -type d -name dist-packages
  - cp -r /usr/local/lib/python2.7/site-packages/* target/robotframework/libraries/ 
  - find . -type f -iname webdriver.py -print
#script: mvn clean install
