language: java
before_install:
  - yes y | python -m pip uninstall pip
  - wget https://bootstrap.pypa.io/get-pip.py | python
  - pip install robotframework-seleniumlibrary
  - find / -type d -iname site-packages -print
#script: mvn clean install
