language: java
sudo: required
before_install:
#  - yes y | sudo python -m pip uninstall pip
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo python get-pip.py 
  - pwd
  - which pip 
  - find . -type f -iname *pip* -print
  - sudo pip install pyOpenSSL ndg-httpsclient pyasn1
  - pip install robotframework-seleniumlibrary
# - find / -type f -iname webdriver.py -print
#script: mvn clean install
