language: java
#sudo: required
before_install:
#  - yes y | sudo python -m pip uninstall pip
  - wget https://bootstrap.pypa.io/get-pip.py | python - --user
  - ls -ltr ~/
  - cd ~
  - ls -ltr
  - find . -type f -iname *pip* -print
#  - pip install robotframework-seleniumlibrary
# - find / -type f -iname webdriver.py -print
#script: mvn clean install
